// ... keep all your existing code above ...

downloadCert?.addEventListener("click", () => {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "A4" });

  // Canvas-like layout values
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const centerX = W / 2;

  // Border
  doc.setDrawColor(40, 40, 40);
  doc.setLineWidth(4);
  doc.rect(24, 24, W - 48, H - 48);

  // Heading
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.text("Certificate of Completion", centerX, 140, { align: "center" });

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.text("ATO Training Game", centerX, 180, { align: "center" });

  // Horizontal rule
  doc.setLineWidth(1);
  doc.line(160, 200, W - 160, 200);

  // Score + status
  const passed = meetsThreshold(score);
  const statusText = passed ? "PASSED" : "FAILED";
  const statusColor = passed ? [16, 185, 129] : [239, 68, 68];

  doc.setFontSize(14);
  doc.text(`Awarded to: ______________________________`, centerX, 260, { align: "center" });
  doc.text(`Final Score: ${score} / ${totalPoints()} (${Math.round((score / totalPoints()) * 100)}%)`, centerX, 295, { align: "center" });

  doc.setTextColor(...statusColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`Status: ${statusText}`, centerX, 330, { align: "center" });

  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");

  // Signature area
  doc.line(W * 0.25, 420, W * 0.45, 420);
  doc.text("Authorized Signature", W * 0.35, 440, { align: "center" });

  doc.line(W * 0.55, 420, W * 0.75, 420);
  const today = new Date().toLocaleDateString();
  doc.text(`Date (${today})`, W * 0.65, 440, { align: "center" });

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ATO Training Game", centerX, H - 40, { align: "center" });

  // Save
  doc.save("ATO-Certificate.pdf");
});

// ... keep the rest of your existing code below ...
